//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClient.CustomerServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.sitels.ru/services/", ConfigurationName="CustomerServices.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.sitels.ru/services/ICustomerService/UpdateCustomerName", ReplyAction="http://schemas.sitels.ru/services/ICustomerService/UpdateCustomerNameResponse")]
        void UpdateCustomerName(int customerId, string customerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.sitels.ru/services/ICustomerService/UpdateCustomerName", ReplyAction="http://schemas.sitels.ru/services/ICustomerService/UpdateCustomerNameResponse")]
        System.Threading.Tasks.Task UpdateCustomerNameAsync(int customerId, string customerName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : ServiceClient.CustomerServices.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<ServiceClient.CustomerServices.ICustomerService>, ServiceClient.CustomerServices.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpdateCustomerName(int customerId, string customerName) {
            base.Channel.UpdateCustomerName(customerId, customerName);
        }
        
        public System.Threading.Tasks.Task UpdateCustomerNameAsync(int customerId, string customerName) {
            return base.Channel.UpdateCustomerNameAsync(customerId, customerName);
        }
    }
}
